[project]
name = "pytest-ayon"
version = "0.1.1"
description = "A pytest plugin for testing AYON and its components."
authors = [
    {name = "YNPUT, s.r.o.", email="team@ynput.io"},
]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/ynput/pytest-ayon"
homepage = "https://github.com/ynput/pytest-ayon"
keywords = ["pytest", "ayon", "testing", "development"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Testing",
    "Framework :: Pytest",
]
requires-python = "==3.11.6"
dependencies = [
    "pytest",
    "ayon-python-api",
    "requests ~= 2.17",
    "ruff>=0.15.7",
]

[project.entry-points.pytest11]
ayon = "pytest_ayon.plugin"

[project.optional-dependencies]
dev = [
    "ruff ~= 0.15.7",
    "pre-commit",
    "codespell",
    "pytest-cov",
    "pytest-print",
    "mypy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "vendor",
    "generated",
]

# Same as Black.
line-length = 79
indent-width = 4
# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
preview = true  # this is needed for linting empty lines, etc.

pydocstyle.convention = "google"

select = ["ALL"]
ignore = [
    "PTH",
    "ANN204",
    "COM812",
    "S603",
    "ERA001",
    "TRY003",
    "UP006",   # support for older python version (type vs. Type)
    "UP007",   # ..^
    "UP035",   # ..
    "UP045",   # Use `X | None` for type annotations
    "ARG002",
    "INP001",  # add `__init__.py` to namespaced package
    "FIX002",  # FIX all TODOs
    "TD003",   # missing issue link
    "S404",    # subprocess module is possibly insecure
    "PLC0415", # import must be on top of the file
    "CPY001",  # missing copyright header
    "UP045",
    "S101",    # use of assert
    "AST100",  # asserts only in tests
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.codespell]
# Ignore words that are not in the dictionary.
ignore-words-list = "ayon,ynput"
skip = "./.*"
count = true
quiet-level = 3
